### ISSUE TITLE
Criar frontend estático - HOME

### ISSUE THREAD

**Issue by samaratiemi** [rosanarezende/Gama-GCP-projeto-final#7]
**Definição de feito:**
Na pasta `app`, criar a pasta `templates` e adicionar os seguintes arquivos:

**Página home**
- [x] Criar front-end index.html (Home)
- [x] Criar a view da home no arquivo app/views.py
- [x] Criar a rota da home no arquivo projeto/urls.py

Desenvolver o front-end com o framework [Bootstrap](https://getbootstrap.com/docs/5.1/examples/) e seguir as imagens da seguinte pasta do [Drive](https://drive.google.com/drive/folders/1TEEqm_6KUCCM-3FAKEX8blNu_Kncu1V-?usp=sharing).
A equipe desenhou as telas em conjunto e adicionou as imagens no Drive.

Home:
![index](https://user-images.githubusercontent.com/45580434/134772884-0ae6942e-31c0-4f73-8676-859b81bb12c0.png)

**Comment by cristina-gomes** [comment]
Pendente a tabela de imagem dos produtos na pagina index.
